// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/get_biggest_change": {
            "get": {
                "description": "Получение адреса, который максимально изменился за count_of_blocks блоков\nПо умолчанию count_of_blocks = 100",
                "tags": [
                    "StatsOfChanging"
                ],
                "summary": "Получение адреса, который максимально",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Количество последних блоков",
                        "name": "count_of_blocks",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Адрес найден",
                        "schema": {
                            "$ref": "#/definitions/entity.BiggestChange"
                        }
                    },
                    "400": {
                        "description": "Ошибка в запросе"
                    },
                    "500": {
                        "description": "Таймаут запроса"
                    }
                }
            }
        }
    },
    "definitions": {
        "entity.BiggestChange": {
            "description": "Наибольшее изменение .",
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "amount": {
                    "type": "string"
                },
                "countOfBlocks": {
                    "type": "integer"
                },
                "isRecieved": {
                    "type": "boolean"
                },
                "lastBlock": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1 .",
	Schemes:          []string{},
	Title:            "Stats Of Changing",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
